// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:teacherapp/features/auth/models/class_info.dart';
import 'package:teacherapp/features/auth/models/punch_in_out.dart';
import 'package:teacherapp/features/auth/models/teacher_user.dart';
import 'package:teacherapp/features/auth/models/teacher_verification.dart';
import 'package:teacherapp/features/curriculum/models/curriculum_role_info.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ClassInfoAdapter());
    registerAdapter(CurriculumRoleInfoAdapter());
    registerAdapter(PunchInOutAdapter());
    registerAdapter(TeacherDetailsAdapter());
    registerAdapter(TeacherUserAdapter());
    registerAdapter(TeacherVerificationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ClassInfoAdapter());
    registerAdapter(CurriculumRoleInfoAdapter());
    registerAdapter(PunchInOutAdapter());
    registerAdapter(TeacherDetailsAdapter());
    registerAdapter(TeacherUserAdapter());
    registerAdapter(TeacherVerificationAdapter());
  }
}
